# Generated by Django 2.1 on 2019-02-11 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20190131_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.Food')),
            ],
        ),
    ]
