# Generated by Django 2.1 on 2019-02-17 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_auto_20190217_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='foods',
            new_name='food',
        ),
    ]
